### ISSUE TITLE
Publish anicollection package to npm

### ISSUE THREAD

**Issue by Den-dp** [anicollection/anicollection#3]
I found that you have [package.json](https://github.com/anicollection/anicollection/blob/master/package.json) but it looks like your package wasn't published to npm.

As an npm user I want to install `anicollection` package with 

```
npm install anicollection --save
```

Here you can get more information about the publishing process:
https://docs.npmjs.com/getting-started/publishing-npm-packages

**Comment by Den-dp** [comment]
:wave: @darielnoel @quitequinn @TimTheTinker

Hi, guys. So what do you think about it?

**Comment by darielnoel** [comment]
+1

**Comment by Den-dp** [comment]
@darielnoel great! Any thoughts what should be done to make it happen?

**Comment by Den-dp** [comment]
Also this screencasts might be useful https://egghead.io/series/how-to-write-an-open-source-javascript-library (look at videos about npm)

**Comment by darielnoel** [comment]
That's it :)

https://www.npmjs.com/package/anicollection

Thanks for your kind advice. I you wanna make some others contributions, you're welcome.

Best Regards, Dariel

**Comment by Den-dp** [comment]
Great!
Thanks a lot @darielnoel
